### ISSUE TITLE
Add Options so people dont try to learn everything

### ISSUE THREAD

**Issue by abughurab16** [66daysofdata/Resources#4]
i noticed that in the machine learning paths you listed several frameworks but i dont think you mentioned that there is no need to learn all of them but rather just pick one and work with it , also there are  other areas that you need to indicate  to have several tools but not all must be learnt

thanks and hope you understood what i meant

**Comment by muric-dev** [comment]
We should create a roadmap for extremely beginners, i can help with that

**Comment by ghost** [comment]
Yeah the road map would be extremely helpful .

**Comment by pabs-lop** [comment]
Sounds good.  There is a lot to learn and we did this in a fast manner.  It is true that you don't need to learn all.  You can pick any ML Framework such as PyTorch.  I hope this is what you are referring too?

Please feel free to contribute.

**Comment by muric-dev** [comment]
If anyone has any ideas, they could make the photo.

**Comment by pabs-lop** [comment]
I have updated the requested above.  Made sure to mention a  recommendation to learn the most popular framework or tool.  Thanks for the suggestions.
